platform :ios, '9.0'
use_frameworks!

workspace 'APISDKFront.xcworkspace'

def apiSdkFront_pods
    pod 'Kingfisher', "~> 3.0"
    pod 'SwiftyJSON', "3.0.0"
    pod 'Crashlytics'
end

def diveApi_pods
    pod 'Alamofire', "~> 4.0"
end


target 'APISDKFront' do
    project '../../api-sdk-front-ios/APISDKFront/APISDKFront.xcodeproj'
    
    apiSdkFront_pods
end

target 'DiveApi' do
    project '../../dive-rest-ios/DiveApi/DiveApi.xcodeproj'
    
    diveApi_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end